services:
  pokemon-showdown:
    build:
      context: .
      dockerfile: Dockerfile
    command: node pokemon-showdown start --no-security
    ports:
      - "8000:8000" # Expose port 8000 for the application
    # For older docker-compose versions or non-swarm deployments,
    # you might need to use 'runtime: nvidia' directly under the service:
    # runtime: nvidia
    #volumes:
    #  - ../..:/workspaces/IIC3675-RL:cached # Mount the project directory
    # Add any other necessary configurations like ports, environment variables, etc.